version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "Running tests"
      - run: yarn
      - run: yarn test
  build:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: echo "build project"
      - run: yarn
      - run: yarn build

workflows:
  version: 2
    test_build:
      jobs:
        - test
        - build:
          requires:
            - test